.TH "_MacrosPrivate::_MacrosIt< IT >" 3 "Mon Jan 6 2020" "Version 0.1.0-a1" "MacrosLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_MacrosPrivate::_MacrosIt< IT >
.SH SYNOPSIS
.br
.PP
.PP
Inherits IT\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef IT \fBTIt\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_MacrosIt\fP (const IT &_begin, const IT &end, bool reverse=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IT \fBbegin\fP"
.br
.ti -1c
.RI "IT \fBend\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MacrosLib from the source code\&.
