.TH "C:/Users/Sig/Dropbox/MacrosLib/src/macroslib.h" 3 "Mon Jan 6 2020" "Version 0.1.0-a1" "MacrosLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Sig/Dropbox/MacrosLib/src/macroslib.h \- Main file for MacrosLib include\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'macropatterns/interfaces\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTRDEF_NO_PREPROCESSOR\fP"
.br
.RI "Macros for disable include preprocessor utils section\&. But if other files depend for them, then ignored\&. "
.ti -1c
.RI "#define \fBSTRDEF_NO_OPERATORS\fP"
.br
.RI "Macros for disable include operators section\&. But if other files depend for them, then ignored\&. "
.ti -1c
.RI "#define \fBSTRDEF_NO_UTILS\fP"
.br
.RI "Macros for disable include code utils section\&. But if other files depend for them, then ignored\&. "
.ti -1c
.RI "#define \fBSTRDEF_MACROPATTERNS\fP"
.br
.RI "Macros for include macropatterns section\&. "
.in -1c
.SH "Detailed Description"
.PP 
Main file for MacrosLib include\&. 

The file contains includes of all library files and macros for managing them\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MacrosLib from the source code\&.
