.TH "md__c_1__users__sig__dropbox__macros_lib__r_e_a_d_m_e" 3 "Mon Jan 6 2020" "Version 0.1.0-a1" "MacrosLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1__users__sig__dropbox__macros_lib__r_e_a_d_m_e \- README 
\fBen_EN\fP \fCru_RU\fP
.PP
.PP
 
.SS "MacrosLib"
.PP
.PP
Last version 0\&.1\&.0-a1
.SS "Table of Contents"
.IP "\(bu" 2
\fCAbout the Project\fP
.IP "\(bu" 2
\fCUsage\fP
.IP "\(bu" 2
\fCLicense\fP
.PP
.SS "About The Project"
You can read \fCThe Change history\fP
.SS "Usage"
Read help for MacrosLib
.SS "License"
Distributed under the MIT License\&. 
