



       
       
       
m ( d , 1) m ( d , 2)
MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( MACRO ( 1, 2, 3 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )
1 = 1
2, 3 = 2, 3
1 = 1
(2, 3) = (2, 3)
1 = 1
(2, 3) = ( 2, 3 )
1 = 1
(1) = (1)
(2, 3) = ( 2, 3 )
(2, 3) = ( 2, 3 )

1 = 1
(2, 3) = ( 2, 3 )
2 = 2
(3) = ( 3 )
1 = 1
(2, 3) = ( 2, 3 )
2 = 2
1 = 1
(3) = ( 3 )
1 = 1
(2, 3) = ( 2, 3 )
(3) = ( 3 )
1 = 1
(4) = ( 4 )
(2, 3) = ( 2, 3 )
2 = 2
1 = 1
1 = 1
(3) = ( 3 )
(2, 3) = ( 2, 3 )
2 = 2
3 = 3
(2, 3) = ( 2, 3 )
1 = 1
(4) = ( 4 )
(3) = ( 3 )
(2, 3) = ( 2, 3 )
1 = 1

1 = 1
2 = 2
3 = 3
4 = 4

1 = 1
5 = 5

6 = 6

2 , 1 , 3, 4 = 2, 1, 3, 4

PP_INVOKE( PP_ITERATE_ITEM , ( ddd , 1)) PP_INVOKE( PP_ITERATE_ITEM , ( ddd , 2)) PP_INVOKE( PP_ITERATE_ITEM , ( ddd , 3)) = 123
PP_INVOKE( PP_ITERATE_ITEM_DATA , ( ddd , 1)) PP_INVOKE( PP_ITERATE_ITEM_DATA , ( ddd , 2)) PP_INVOKE( PP_ITERATE_ITEM_DATA , ( ddd , 3)) = ddddddddd
PP_INVOKE( PP_ITERATE_ITEM_APPEND , ( (a, b, c) , 1)) PP_INVOKE( PP_ITERATE_ITEM_APPEND , ( (a, b, c) , 2)) PP_INVOKE( PP_ITERATE_ITEM_APPEND , ( (a, b, c) , 3)) = (a, b, c, 1, 2, 3)
PP_INVOKE( PP_ITERATE_ITEM_PREPEND , ( (a, b, c) , 1)) PP_INVOKE( PP_ITERATE_ITEM_PREPEND , ( (a, b, c) , 2)) PP_INVOKE( PP_ITERATE_ITEM_PREPEND , ( (a, b, c) , 3)) = (1, 2, 3, a, b, c)
PP_INVOKE( PP_ITERATE_ITEM_MACRO , ( MACRO , 1)) PP_INVOKE( PP_ITERATE_ITEM_MACRO , ( MACRO , 2)) PP_INVOKE( PP_ITERATE_ITEM_MACRO , ( MACRO , 3)) = MACRO(1)MACRO(2)MACRO(3)
PP_INVOKE( PP_ITERATE_ITEM_SEP , ( SEP , 1)) PP_INVOKE( PP_ITERATE_ITEM_SEP , ( SEP , 2)) PP_INVOKE( PP_ITERATE_ITEM_SEP , ( SEP , 3)) = SEP 1 SEP 2 SEP 3
PP_INVOKE( PP_ITERATE_ITEM_COMMA , ( MACRO , 1)) PP_INVOKE( PP_ITERATE_ITEM_COMMA , ( MACRO , 2)) PP_INVOKE( PP_ITERATE_ITEM_COMMA , ( MACRO , 3)) = , MACRO(1) , MACRO(2) , MACRO(3)
PP_INVOKE( PP_ITERATE_ITEM_FOLDR , ( MACRO , 1)) PP_INVOKE( PP_ITERATE_ITEM_FOLDR , ( MACRO , 2)) PP_INVOKE( PP_ITERATE_ITEM_FOLDR , ( MACRO , 3)) = MACRO(1 MACRO(2 MACRO(3
PP_INVOKE( PP_ITERATE_ITEM_FOLDL , ( _ , 1)) PP_INVOKE( PP_ITERATE_ITEM_FOLDL , ( _ , 2)) PP_INVOKE( PP_ITERATE_ITEM_FOLDL , ( _ , 3)) = , 1) , 2) , 3)

PP_INVOKE( PP_ITERATE_ITEM , ( _ , 1)) PP_INVOKE( PP_ITERATE_ITEM , ( _ , 2)) PP_INVOKE( PP_ITERATE_ITEM , ( _ , 3)) = 123

PP_INVOKE( PP_ITERATE_ITEM_MACRO , ( MACRO , 1)) PP_INVOKE( PP_ITERATE_ITEM_MACRO , ( MACRO , 2)) PP_INVOKE( PP_ITERATE_ITEM_MACRO , ( MACRO , 3)) = MACRO(1)MACRO(2)MACRO(3)

1 PP_INVOKE( PP_ITERATE_ITEM_SEP , ( SEP , PP_VA_TAIL (1, 2, 3))) = 1 SEP 2 SEP 3

MACRO (1) PP_INVOKE( PP_ITERATE_ITEM_MACRO , ( SEP MACRO , PP_VA_TAIL (1, 2, 3))) = MACRO(1) SEP MACRO(2) SEP MACRO(3)

PP_INVOKE(PP_ITERATE_PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (PP_ITERATE_ITEM_APPEND, 4, (1, 2, 3), (1, 2, 3), (1, 2, 3) , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,PP_ITERATE_ITEM_APPEND, 4, (1, 2, 3), (1, 2, 3), (1, 2, 3)), (PP_ITERATE_ITEM_APPEND, 4, (1, 2, 3), (1, 2, 3), (1, 2, 3))) = (1, 2, 3, 4), (1, 2, 3, 4), (1, 2, 3, 4)

PP_INVOKE(PP_ITERATE_PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (PP_ITERATE_ITEM_PREPEND, 4, (1, 2, 3), (1, 2, 3), (1, 2, 3) , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,PP_ITERATE_ITEM_PREPEND, 4, (1, 2, 3), (1, 2, 3), (1, 2, 3)), (PP_ITERATE_ITEM_PREPEND, 4, (1, 2, 3), (1, 2, 3), (1, 2, 3))) = (4, 1, 2, 3), (4, 1, 2, 3), (4, 1, 2, 3)

MACRO (1) PP_INVOKE( PP_ITERATE_ITEM_COMMA , ( MACRO , PP_VA_TAIL (1, 2, 3))) = MACRO(1), MACRO(2), MACRO(3)

PP_INVOKE( MACRO , (PP_INVOKE( PP_HEAD, (1, 2, 3) ))) PP_INVOKE(PP_ITERATE_PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (PP_ITERATE_ITEM_MACRO, SEP MACRO, PP_INVOKE( PP_VA_TAIL, (1, 2, 3) ) , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,PP_ITERATE_ITEM_MACRO, SEP MACRO, PP_INVOKE( PP_VA_TAIL, (1, 2, 3) )), (PP_ITERATE_ITEM_MACRO, SEP MACRO, PP_INVOKE( PP_VA_TAIL, (1, 2, 3) ))) = MACRO(1) SEP MACRO(2) SEP MACRO(3)

PP_INVOKE( macro , 1 ) , PP_VA_FUNC(PP_ITERATE, PP_ITERATE_ITEM_DATA, PP_INVOKE( macro , ( 1 )), PP_INVOKE( PP_VA_GEN_A_N, ( PP_INVOKE( PP_VA_DECREMENT, ( 5 )) ) )) = 1, 1, 1, 1, 1
PP_INVOKE( MACRO , 1 ) , PP_VA_FUNC(PP_ITERATE, PP_ITERATE_ITEM_DATA, PP_INVOKE( MACRO , ( 1 )), PP_INVOKE( PP_VA_GEN_A_N, ( PP_INVOKE( PP_VA_DECREMENT, ( 5 )) ) )) = MACRO(1), MACRO(1), MACRO(1), MACRO(1), MACRO(1)
PP_INVOKE( MACRO , 1 ) SEP PP_VA_FUNC(PP_ITERATE, PP_ITERATE_ITEM_DATA, separator PP_INVOKE( MACRO , ( 1 )), PP_INVOKE( PP_VA_GEN_A_N, ( PP_INVOKE( PP_VA_DECREMENT, ( 5 )) ) )) = MACRO(1) SEP MACRO(1) SEP MACRO(1) SEP MACRO(1) SEP MACRO(1)

PP_INVOKE( PP_ITERATE_ITEM_FOLDR , ( MACRO , a)) PP_INVOKE( PP_ITERATE_ITEM_FOLDR , ( MACRO , b)) PP_INVOKE( PP_ITERATE_ITEM_FOLDR , ( MACRO , c)) , 123 PP_INVOKE( PP_INSERT_CLOSE_PAREN , _ ) PP_VA_FUNC(PP_ITERATE, PP_ITERATE_ITEM_DATA, separator PP_INVOKE( PP_INSERT_CLOSE_PAREN , ( _ )), PP_INVOKE( PP_VA_GEN_A_N, ( PP_INVOKE( PP_VA_DECREMENT, ( 3 )) ) )) ) ) = MACRO( a, MACRO( b, MACRO( c, 123 ) ) )
PP_INVOKE( PP_OPEN_FUNC , MACRO ) PP_VA_FUNC(PP_ITERATE, PP_ITERATE_ITEM_DATA, separator PP_INVOKE( PP_OPEN_FUNC , ( MACRO )), PP_INVOKE( PP_VA_GEN_A_N, ( PP_INVOKE( PP_VA_DECREMENT, ( 3 )) ) )) ) 123 PP_INVOKE( PP_ITERATE_ITEM_FOLDL , ( _ , a)) PP_INVOKE( PP_ITERATE_ITEM_FOLDL , ( _ , b)) PP_INVOKE( PP_ITERATE_ITEM_FOLDL , ( _ , c)) = MACRO( MACRO( MACRO( 123, a), b), c)
PP_INVOKE(PP_REPEAT_PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (PP_OPEN_FUNC , MACRO , PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (a, b, c , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,a, b, c), , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,PP_OPEN_FUNC , MACRO , PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (a, b, c , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,a, b, c),), (PP_OPEN_FUNC , MACRO , PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (a, b, c , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,a, b, c),)) ) 123 PP_INVOKE(PP_ITERATE_PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (PP_ITERATE_ITEM_FOLDL, _, a, b, c , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,PP_ITERATE_ITEM_FOLDL, _, a, b, c), (PP_ITERATE_ITEM_FOLDL, _, a, b, c)) = MACRO( MACRO( MACRO( 123, a), b), c)

MACRO1 ( PP_INVOKE( PP_ITERATE_ITEM_COMMA , ( PP_OPEN_FUNC , PP_VA_TAIL (MACRO1, MACRO2, MCARO3))) 1, 2, 3 PP_INVOKE( PP_ITERATE_ITEM_FOLDL , ( _ , MACRO1)) PP_INVOKE( PP_ITERATE_ITEM_FOLDL , ( _ , MACRO2)) PP_INVOKE( PP_ITERATE_ITEM_FOLDL , ( _ , MCARO3)) = MACRO1(MACRO2(MACRO3(1, 2, 3)))

PP_MAP( PP_OPEN_FUNC , ) PP_INVOKE( PP_APPLY, PP_INVOKE(PP_APPLY, PP_INVOKE(PP_SKIP_OR_CHOOSE, (PP_INSERT_COMMA PP_INVOKE( PP_INVERSE_CHOOSE, (PP_PP_INVOKE( PP_CHOOSE_FIRST, (PP_COMMA_WORD PP_REMOVE PP_INVOKE( PP_ITERATE , (PP_ITERATE_ITEM_APPEND, ( MACRO1, MACRO2, MCARO3 ) , 1, 2, 3) ) ())), true, )) () ((PP_INVOKE( PP_ITERATE , (PP_ITERATE_ITEM_APPEND, ( MACRO1, MACRO2, MCARO3 ) , 1, 2, 3) ))), (PP_INVOKE( PP_ITERATE , (PP_ITERATE_ITEM_APPEND, ( MACRO1, MACRO2, MCARO3 ) , 1, 2, 3) )))))) PP_INVOKE(PP_ITERATE_PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (PP_ITERATE_ITEM_FOLDL, _, , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,PP_ITERATE_ITEM_FOLDL, _,), (PP_ITERATE_ITEM_FOLDL, _,)) PP_INVOKE( PP_ITERATE_ITEM_COMMA , ( PP_COMPOSE , PP_VA_TAIL (PP_INVOKE( PP_ITERATE , (PP_ITERATE_ITEM_APPEND, ( MACRO1, MACRO2, MCARO3 ) , 1, 2, 3) )))) = MACRO1(MACRO2(MACRO3(1))), MACRO1(MACRO2(MACRO3(2))), MACRO1(MACRO2(MACRO3(3)))

PP_INVOKE(PP_ITERATE_PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (PP_ITERATE_ITEM_FOLDR, PP_SWAP, 2, 3 , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,PP_ITERATE_ITEM_FOLDR, PP_SWAP, 2, 3), (PP_ITERATE_ITEM_FOLDR, PP_SWAP, 2, 3)) , 1 PP_INVOKE(PP_REPEAT_PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (PP_INSERT_CLOSE_PAREN , _ , PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (2, 3 , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,2, 3), , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,PP_INSERT_CLOSE_PAREN , _ , PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (2, 3 , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,2, 3),), (PP_INSERT_CLOSE_PAREN , _ , PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (2, 3 , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,2, 3),)) ) ) = 3, 2, 1

PP_INVOKE) = (2, 3), (2, 3), (2, 3)

PP_INVOKE(PP_APPLY, PP_INVOKE(PP_SKIP_OR_CHOOSE, (PP_INSERT_COMMA PP_INVOKE( PP_INVERSE_CHOOSE, (PP_PP_INVOKE( PP_CHOOSE_FIRST, (PP_COMMA_WORD PP_REMOVE PP_INVOKE( PP_TAIL, PP_INVOKE(PP_APPLY, PP_INVOKE(PP_SKIP_OR_CHOOSE, (PP_INSERT_COMMA PP_INVOKE( PP_INVERSE_CHOOSE, (PP_PP_INVOKE( PP_CHOOSE_FIRST, (PP_COMMA_WORD PP_REMOVE 1 ())), true, )) () ((1)), (1)))) ) ())), true, )) () ((PP_INVOKE( PP_TAIL, PP_INVOKE(PP_APPLY, PP_INVOKE(PP_SKIP_OR_CHOOSE, (PP_INSERT_COMMA PP_INVOKE( PP_INVERSE_CHOOSE, (PP_PP_INVOKE( PP_CHOOSE_FIRST, (PP_COMMA_WORD PP_REMOVE 1 ())), true, )) () ((1)), (1)))) ))), (PP_INVOKE( PP_TAIL, PP_INVOKE(PP_APPLY, PP_INVOKE(PP_SKIP_OR_CHOOSE, (PP_INSERT_COMMA PP_INVOKE( PP_INVERSE_CHOOSE, (PP_PP_INVOKE( PP_CHOOSE_FIRST, (PP_COMMA_WORD PP_REMOVE 1 ())), true, )) () ((1)), (1)))) ))))) PP_INVOKE( PP_ITERATE_ITEM_COMMA , ( PP_TAIL_PAREN , PP_VA_TAIL (1, 2, 3))) = (1, 2, 3), (2, 3), (1)

PP_INVOKE( PP_HEAD, PP_INVOKE(PP_APPLY, PP_INVOKE(PP_SKIP_OR_CHOOSE, (PP_INSERT_COMMA PP_INVOKE( PP_INVERSE_CHOOSE, (PP_PP_INVOKE( PP_CHOOSE_FIRST, (COMMA)), true, )) () (((1, 2, 3))), ((1, 2, 3))))) ) PP_INVOKE( PP_ITERATE_ITEM_COMMA , ( PP_HEAD_PAREN , PP_VA_TAIL ((1, 2, 3), (1, 2, 3), (1, 2, 3)))) = (1, 1, 1)

PP_INVOKE) = (1, 1), (2, 2), (3, 3)

PP_CAT_PAREN) PP_INVOKE( PP_ITERATE_ITEM_COMMA , ( PP_CAT_PAREN , PP_VA_TAIL (PP_INVOKE))) ) = (1, 2, 3, 4), (1, 2, 3, 4), (1, 2, 3, 4)

PP_CAT_PAREN) PP_INVOKE( PP_ITERATE_ITEM_COMMA , ( PP_CAT_PAREN , PP_VA_TAIL (PP_INVOKE))) ) = (4, 1, 2, 3), (4, 1, 2, 3), (4, 1, 2, 3)

PP_INVOKE(PP_REPEAT_PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (PP_OPEN_FUNC , PP_MASS_APPEND , PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, ((1, 1), (2, 2), (3, 3) , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,(1, 1), (2, 2), (3, 3)), , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,PP_OPEN_FUNC , PP_MASS_APPEND , PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, ((1, 1), (2, 2), (3, 3) , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,(1, 1), (2, 2), (3, 3)),), (PP_OPEN_FUNC , PP_MASS_APPEND , PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, ((1, 1), (2, 2), (3, 3) , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,(1, 1), (2, 2), (3, 3)),)) ) ( PP_INVOKE( PP_INSERT_EMPTY_LIST , _ ) , PP_VA_FUNC(PP_ITERATE, PP_ITERATE_ITEM_DATA, PP_INVOKE( PP_INSERT_EMPTY_LIST , ( _ )), PP_INVOKE( PP_VA_GEN_A_N, ( PP_INVOKE( PP_VA_DECREMENT, ( 1 )) ) )) ) PP_INVOKE(PP_ITERATE_PP_INVOKE(PP_CAT, (PP_VA_SIZE_, PP_INVOKE( PP_VA_GET_A, (PP_ITERATE_ITEM_FOLDL, _, (1, 1), (2, 2), (3, 3) , 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 1N, 01, _) ) )) (,PP_ITERATE_ITEM_FOLDL, _, (1, 1), (2, 2), (3, 3)), (PP_ITERATE_ITEM_FOLDL, _, (1, 1), (2, 2), (3, 3))) (1, 2, 3), (1, 2, 3)
